### ISSUE TITLE
vagrant up box version issues

### ISSUE THREAD

**Issue by morwick8** [udacity/fullstack-nanodegree-vm#113]
michelle@michelle-PC MINGW64 ~/FullStack/vagrant (master)
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: = 2.3.5
==> default: Loading metadata for box 'bento/ubuntu-16.04'
    default: URL: https://vagrantcloud.com/bento/ubuntu-16.04
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: bento/ubuntu-16.04
Address: https://vagrantcloud.com/bento/ubuntu-16.04
Constraints: = 2.3.5
Available versions: 201801.02.0, 201802.02.0, 201803.24.0, 201806.08.0, 201807.12.0, 201808.24.0, 201812.15.0, 201812.27.0, 201906.18.0, 201910.20.0, 201910.21.0, 201910.31.0, 201912.03.0, 201912.04.0, 201912.15.0

**Comment by wcouturiaux** [comment]
Also seeing this issue. I was not able to install virtual box 5.1 on MacOS Cantalina. I'm glad I'm not paying udacity this round. They really need to keep up with this stuff.

**Comment by wcouturiaux** [comment]
I was able to go into the vagrant file and on line 5 change config.vm.box = "bento/ubuntu-16.04" to config.vm.box = "bento/ubuntu-16.04-i386" and it runs. I'm not fully working yet but..

**Comment by Mathew-Walsh** [comment]
@wcouturiaux I've altered line 5 as you mentioned, thankfully my VM is now downloading! Taken days to try and figure this out and I came nowhere near solving this! I'd even tried the older versions as recommended by Udacity! 

How did you figure out the resolve?

P.S. Thank you for helping fix the issue!

**Comment by wcouturiaux** [comment]
@Mathew-Walsh when I searched google, I noticed there was no bento/ubuntu-16.04 available from vagrant. The closed was with the -i386 so I gave it a whirl and it worked. It took me a few days to get there though!

No problem! glad I was able to resolve, I was beyond frustrated, but got to learn a little extra! lol

**Comment by morwick8** [comment]
Thank you so much for the assistance!

**Comment by Aryan-tagteen** [comment]
Love you wcouturiaux, was struggling from past3 hours.

**Comment by Reeteekah** [comment]
Thanks for this! 
You may also try setting Vagrantfile config.vm.box_version = "202112.19.0", has worked for me.
