### ISSUE TITLE
Could not vagrant up

### ISSUE THREAD

**Issue by frank-yuan** [udacity/fullstack-nanodegree-vm#37]
Do I have to log in? When I want to sign up, I found there is no way to do that.

![image](https://cloud.githubusercontent.com/assets/2692611/20638064/99a2b1dc-b371-11e6-86b2-a669bf6c27a9.png)

**Comment by twhetzel** [comment]
@frank-yuan no, you shouldn't have to. What version of Vagrant did you install? What version of MacOS are you running?

**Comment by frank-yuan** [comment]
Hi @twhetzel ,
I installed vagrant  1.8.7 and VirtualBox 5.1.10 on my OSX 10.12.
Thanks.

**Comment by twhetzel** [comment]
Hi @frank-yuan - I suspect you are running into this issue: 
https://github.com/mitchellh/vagrant/issues/7997

The two workarounds are to either install Vagrant 1.8.6 or run this command to remove Vagrant's version of curl:
`sudo rm -f /opt/vagrant/embedded/bin/curl`

**Comment by frank-yuan** [comment]
@twhetzel Perfect, it works! Thank you for your help!

**Comment by twhetzel** [comment]
Sure thing! Glad it's working now. If you have any other questions on the projects themselves, there are a lot of folks that monitor the Udacity Discussion forums.
