### ISSUE TITLE
apt-get update and apt-get upgrade do not get run

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fullstack-nanodegree-vm#56]
Hello,

In the new version of the `Vagrantfile`, there are these lines that are suppose to update the VM:

```
apt-get update
apt-get upgrade
```

However, without the `-y` option, these command wait for user input, then defaults to not doing anything. It would be probably best to use the options that were in the old `pg_config.sh` to fix this:

```
apt-get -qqy update
apt-get -qqy upgrade
```

This will keep things quiet and run the commands.

Let me know if you want me to file a pull request.

Regards,

Steve.

**Comment by karlud** [comment]
Thanks for catching these! This is in flux due to a forthcoming launch.
Sorry for the disruption!

**Comment by twhetzel** [comment]
@karlud is it possible to create a branch and release the updated Vagrantfile when the launch occurs?
These changes can put Udacity mentors and students in an awkward position.

**Comment by SteveWooding** [comment]
You're welcome. It wouldn't matter too much, but for the fact that the Zip file of this repository got updated on the "[Installing the Virtual Machine](https://classroom.udacity.com/nanodegrees/nd004/parts/af045689-1d81-46e7-8a3b-ad05de1142ce/modules/353202897075460/lessons/3423258756/concepts/14c72fe3-e3fe-4959-9c4b-467cf5b7c3a0)" page.
