### ISSUE TITLE
Only Python3 packages are getting installed - not Python2 ones

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fullstack-nanodegree-vm#61]
Hi Karl,

Unfortunately with Ubuntu 16.04, the `pip` command installs the Python3 packages, so it is the same as running `pip3`.

To install Python2 packages, the command `pip2` needs to be run. So you could change this section of the Vagrantfile to:

```
    apt-get -qqy install python python-pip
    pip2 install --upgrade pip
    pip2 install flask packaging oauth2client redis passlib flask-httpauth
    pip2 install sqlalchemy flask-sqlalchemy psycopg2 bleach
```

Though strangely, a side affect after these commands is that `pip` then points to Python2 afterwards. Not sure why that would be.

Regards,

Steve.

**Comment by karlud** [comment]
Thanks for catching this. Fixed.

**Comment by twhetzel** [comment]
You're welcome
