### ISSUE TITLE
`vagrant up` doesn’t complete because of `grub-pc` installation prompt

### ISSUE THREAD

**Issue by twhetzel** [udacity/fullstack-nanodegree-vm#69]
@karlud  Students are currently reporting issues [1,2] with launching Vagrant and getting an error message referring to `Setting up grub-pc`. I came across this post [3] that has resolved this issue for one of the students so far. Perhaps this change should be added to the `Vagrantfile` here in this Udacity repo?

[1] https://discussions.udacity.com/t/vagrant-up-doesnt-complete-because-of-grunt-pc-installation-prompt/274252
[2] https://discussions.udacity.com/t/vagrant-up-stuck-in-the-middle-and-never-complete/275599
[3] https://github.com/chef/bento/issues/661#issuecomment-248136601

**Comment by MissT17** [comment]
The fix worked perfectly.

**Comment by zach-caldwell** [comment]
I had this same issue today and can confirm that this fix solved it.

**Comment by SteveWooding** [comment]
Hi Trish,

Thanks for raising this issue. I have also emailed FSND support. Hopefully this will be addressed soon.

One slight point. You might want to edit the title of the issue, as I was a bit confused by the "grunt-pc" part.

Regards,

Steve.

**Comment by twhetzel** [comment]
The `grunt-pc` part is the distinguising part of the error message ansd what led me to the proposed solution. Is there some other additional text you'd suggest to make it more clear?

**Comment by SteveWooding** [comment]
Ah, I see. The forum post had the title with "grunt-pc" in it, but the actual error mentions the error to do with the "grub-pc" package.

**Comment by karlud** [comment]
Thanks for reporting this!

**Comment by karlud** [comment]
I think that should do it. I'll propagate this into the zip downloads shortly.
