### ISSUE TITLE
Typo in Kevitsa DC Forward Similation

### ISSUE THREAD

**Issue by hal98x** [udacity/fullstack-nanodegree-vm#81]
performed is misspelled in the first line of the paragraph under the survey heading.

Survey
Direct current (DC) resisistivity and IP survey have been perforemd by using Titan24

**Comment by SteveWooding** [comment]
Hi Hal,

This issue doesn't sound like it is related to this repository or the Fullstack Nanodegree. Can you confirm which Udacity Nanodegree you've spotted the typo?
